"""Add session created at for attendance table

Revision ID: 13fb8d5bca39
Revises: 369e45d3b141
Create Date: 2025-05-18 11:28:40.455147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13fb8d5bca39'
down_revision: Union[str, None] = '369e45d3b141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('session_created_at', sa.DateTime(), nullable=True))
    op.add_column('attendance', sa.Column('session_ended_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'session_ended_at')
    op.drop_column('attendance', 'session_created_at')
    # ### end Alembic commands ###
