"""added session id and open close time

Revision ID: 9d27d0f997f0
Revises: a1676ac5410f
Create Date: 2025-05-13 11:14:19.222121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d27d0f997f0'
down_revision: Union[str, None] = 'a1676ac5410f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('session_id', sa.String(), nullable=False))
    op.add_column('attendance', sa.Column('closed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'closed')
    op.drop_column('attendance', 'session_id')
    # ### end Alembic commands ###
