"""added lecturers and course link

Revision ID: a1676ac5410f
Revises: 694c0f79807e
Create Date: 2025-05-11 15:41:02.391783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1676ac5410f'
down_revision: Union[str, None] = '694c0f79807e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecturers',
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('lecturer_id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('courses', sa.Column('lecturer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'lecturers', ['lecturer_id'], ['lecturer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'lecturer_id')
    op.drop_table('lecturers')
    # ### end Alembic commands ###
